## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: quick checks @ci
  run: make check-ci
  change: 
    - Cargo.toml
    - src/**
    - tests/**
  run_on_init: true

- name: nix flake 
  run: 
    - make nix-build-local
    - make nix-build
  change: 
    - Cargo.toml
    - src/**
    - tests/**
    - "*.nix"
  run_on_init: true

- name: stage files in git
  run: 
    - git add {{relative_path}}
    - git add -p
  change: 
    - Cargo.toml
    - "*.md"
    - src/**
    - tests/**
    - "*.nix"
