## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: build project
  run: 
    - cargo build
  change: 
    - Cargo.toml
    - build.rs
    - src/**
    - tests/**
  run_on_init: true

- name: quick checks
  run: 
    - cargo build
    - cargo test
  change: 
    - Cargo.toml
    - src/**
    - tests/**
  run_on_init: true

- name: lint & formatters
  run: 
    - cargo fmt
  change: 
    - Cargo.toml
    - src/**
    - tests/**

- name: nix flake 
  run: 
    - make nix-build-local
    - make nix-build
  change: 
    - Cargo.toml
    - src/**
    - tests/**
    - "*.nix"
  run_on_init: true

- name: stage files in git
  run: 
    - git add {{relative_path}}
    - git add -p
  change: 
    - Cargo.toml
    - "*.md"
    - src/**
    - tests/**
    - "*.nix"
