[ponos]
nvim = { source = "./examples/from/nvim", target = "./examples/to/nvim" }
zsh = { source = "./examples/from/zshrc", target = "./examples/to/.zshrc" }
other = { source = "./examples/from/other", target = "./examples/to/.other" }

[ponos."with-hooks"]
source = "./examples/from/hooks"
target = "./examples/to/.hooks"
[ponos."with-hooks".hooks]
pre_enable = "echo 'Running pre_enable hook for with-hooks'"
pre_disable = "echo 'Running pre_disable hook for with-hooks'"
