[packages]
# This is an example when the target already exist and isn't a link
notlink = { source = "examples/from/zshrc", target = "examples/to/.gitkeep" }
nvim = { source = "examples/from/nvim", target = "examples/to/nvim" }
doesnexist = { source = "examples/from/unknown", target = "examples/to/unknown" }
