name: Periodic checks

on:
  workflow_dispatch:
  schedule:
    # Ever 3 hours
    - cron: '0 */3 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-with-nix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check all flakes
        run: make nix-checks

      - name: Check main nix flake
        run: make nix-build
          
      - name: Check nix flake \#nightly
        run: make nix-build-nightly
